SELECT 
  tblLocations.LocSTATN_ORG_ID AS Org_Code, 
  Mid(tblLocations.StationID, 6, 4) AS Park_Code, 
  tblLocations.StationID AS Location_ID, 
  tblLocations.[Station Name] AS Location_Name, 
  tblLocations.LocationType AS Location_Type, 
  tblLocations.[Decimal Degrees Latitude] AS Latitude, 
  tblLocations.[Decimal Degrees Longitude] AS Longitude, 
  tblLocations.[Geopositioning Method] AS Lat_Lon_Method, 
  tblLocations.[Geopositioning Datum] AS Lat_Lon_Datum, 
  tblLocations.Scale AS Source_Map_Scale_Numeric, 
  "" AS Lat_Lon_Accuracy, 
  "" AS Lat_Lon_Accuracy_Unit, 
  tblLocations.Description AS Location_Description, 
  tblLocations.[Travel Directions] AS Travel_Directions, 
  tblLocations.LocationPurpose AS Location_Purpose, 
  "" AS Establishment_Date, 
  tblLocations.HUC AS HUC8_Code, 
  "" AS HUC12_Code, 
  "" AS Alternate_Location_ID, 
  "" AS Alternate_Location_ID_Context, 
  tblLocations.Elevation AS Elevation, 
  tblLocations.[Elevation Units] AS Elevation_Unit, 
  tblLocations.[Elevation Method] AS Elevation_Method, 
  tblLocations.[Elevation Datum] AS Elevation_Datum, 
  tblLocations.ElevationAccuracy AS Elevation_Accuracy, 
  "ft" AS Elevation_Accuracy_Unit, 
  "US" AS Country_Code, 
  tblLocations.State AS State_Code, 
  tblLocations.County AS County_Name, 
  tblLocations.DrainageArea AS Drainage_Area, 
  tblLocations.DrainageAreaUnits AS Drainage_Area_Unit, 
  tblLocations.ContributingDrainageArea AS Contributing_Area, 
  tblLocations.DrainageAreaUnits AS Contributing_Area_Unit, 
  "" AS Tribal_Land_Indicator, 
  "" AS Tribal_Land_Name, 
  "" AS Well_ID, 
  "" AS Well_Type, 
  "" AS Aquifer_Name, 
  "" AS Formation_Type, 
  "" AS Well_Hole_Depth, 
  "" AS [Well Hole_Depth_Unit], 
  "" AS Well_Status 
FROM 
  tblLocations 
WHERE 
  tblLocations.LocSTATN_IS_NUMBER > 0;
